language: rust
rust:
    - stable
    - beta
    - nightly
matrix:
    include:
        - rust: nightly
          install:
              - rustup component add rustfmt-preview --toolchain=nightly
              - "cargo +nightly install clippy || :"  # install or return True if already installed (don't fail build)
          script:
              - cargo +nightly fmt --all -- --write-mode=diff
              - cargo +nightly clippy --all
    allow_failures:
        - rust: nightly
cache: cargo
install:
    - cargo build --all
script:
    - cargo test --all
